---
name: Dr. Björn C.
surname: Rall
position: "Computational Ecologist, Biostatistician, and Lecturer"
orcid: 0000-0002-3191-8389
publons: G-1508-2013
googlescholar: kxLDLlMAAAAJ&hl
github: b-c-r
linkedin: bjoern-c-rall
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 027d00
header-includes:
  - \definecolor{linkscolor}{HTML}{001594}
  - \hypersetup{colorlinks=true,
                linkcolor=linkscolor,
                filecolor=linkscolor,
                urlcolor=linkscolor,
                urlbordercolor=linkscolor}
output:
  vitae::awesomecv:
    page_total: true
csl: data/bibstyle_current-biology.csl
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = "pdf_cv_files") }) 
---

```{r setup, include=FALSE}
#### design settings for the output ####
sort_year_desc <- TRUE                                                          # sort the publications descending (latest first) or ascending (oldest first)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)           # default settings for CV output

# load packages:
library(vitae)                                                                  # required package for knitting LaTeX CVs from RMarkdown
# library(tibble)                                                                 # For data structure
# library(readr)                                                                  # import data in an elegant way
# library(dplyr)                                                                  # data wrangling
# library(lubridate)                                                              # time data manipulation
```

# Articles (peer reviewed)

```{r articles}
if(sort_year_desc){
  bibliography_entries("data/bib_articles.bib") %>%
    arrange(desc(issued), author$family)
} else{
  bibliography_entries("data/bib_articles.bib") %>%
    arrange(desc(issued), author$family)
}
```

# Book Chapters

```{r book_chapters}
if(sort_year_desc){
  bibliography_entries("data/bib_book_chapters.bib") %>%
    arrange(desc(issued), author$family)
} else{
  bibliography_entries("data/bib_book_chapters.bib") %>%
    arrange(desc(issued), author$family)
}
```

# Code Publications

```{r code_publications}
#bibliography_entries("data/code_publications.bib") %>%
#  arrange(desc(issued), author$family)
```

# Data Publications

```{r data_publications}
#bibliography_entries("data/data_publications.bib") %>%
#  arrange(desc(issued), author$family)
```

# Pre- and Postprints

```{r preprints}
if(sort_year_desc){
  bibliography_entries("data/bib_preprints.bib") %>%
    arrange(desc(issued), author$family)
} else{
  bibliography_entries("data/bib_preprints.bib") %>%
    arrange(desc(issued), author$family)
}
```


```{r eval=FALSE, include=FALSE}
## helpful resources, thx to the authors:
# https://stackoverflow.com/questions/26174565/r-in-rstudio-how-do-i-make-knitr-output-to-a-different-folder-to-avoid-clutteri
```


